In [1]:
!pip install numpy


[notice] A new release of pip is available: 23.3.2 -> 24.2
[notice] To update, run: pip install --upgrade pip


In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 26.2 ms, sys: 29.6 ms, total: 55.8 ms
Wall time: 55.2 ms


In [4]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 565 ms, sys: 176 ms, total: 742 ms
Wall time: 751 ms


In [5]:
import numpy as np
# Генерация случайных данных
data = np.random.rand(2,3)
data

array([[0.12667118, 0.71330934, 0.03719184],
       [0.07723632, 0.2664683 , 0.72426101]])

In [6]:
data * 10

array([[1.26671177, 7.13309339, 0.37191835],
       [0.77236323, 2.66468296, 7.24261009]])

In [7]:
data + data

array([[0.25334235, 1.42661868, 0.07438367],
       [0.15447265, 0.53293659, 1.44852202]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

In [10]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
import numpy as np
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int64')

In [16]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
import numpy as np
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
import numpy as np
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [23]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [24]:
import numpy as np
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [25]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [26]:
import numpy as np
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [27]:
import numpy as np
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [29]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [30]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [33]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [34]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [35]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr[5]

np.int64(5)

In [37]:
arr[5:8]

array([5, 6, 7])

In [38]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [39]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [40]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [41]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [42]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [43]:
arr2d[0][2]

np.int64(3)

In [44]:
arr2d[0, 2]

np.int64(3)

In [45]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3d[1, 0]

array([7, 8, 9])

In [50]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [51]:
x[0]

array([7, 8, 9])

In [52]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [53]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [57]:
arr2d[:2, 2]

array([3, 6])

In [58]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [59]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Булево индексирование

In [60]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [61]:
data

array([[-0.13815771, -0.80074453, -0.94475482,  0.42506247],
       [-0.63723133,  0.29075391, -0.49656571, -0.71325282],
       [-0.72402537, -1.05071225,  1.11418813, -0.91003131],
       [ 0.42499197, -0.79248955, -0.20310352, -0.80882149],
       [-0.48836748,  0.13455937, -0.22686739,  2.33568588],
       [-0.10311708,  1.10141291,  0.26329184,  0.58786465],
       [-1.84549744, -0.39222806, -0.27263346,  1.352671  ]])

In [62]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [63]:
data[names == 'Bob']

array([[-0.13815771, -0.80074453, -0.94475482,  0.42506247],
       [ 0.42499197, -0.79248955, -0.20310352, -0.80882149]])

In [64]:
data[names == 'Bob', 2:]

array([[-0.94475482,  0.42506247],
       [-0.20310352, -0.80882149]])

In [65]:
data[names == 'Bob', 2]

array([-0.94475482, -0.20310352])

In [66]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [67]:
data[~(names == 'Bob')]

array([[-0.63723133,  0.29075391, -0.49656571, -0.71325282],
       [-0.72402537, -1.05071225,  1.11418813, -0.91003131],
       [-0.48836748,  0.13455937, -0.22686739,  2.33568588],
       [-0.10311708,  1.10141291,  0.26329184,  0.58786465],
       [-1.84549744, -0.39222806, -0.27263346,  1.352671  ]])

In [68]:
cond = names == 'Bob'
data[~cond]

array([[-0.63723133,  0.29075391, -0.49656571, -0.71325282],
       [-0.72402537, -1.05071225,  1.11418813, -0.91003131],
       [-0.48836748,  0.13455937, -0.22686739,  2.33568588],
       [-0.10311708,  1.10141291,  0.26329184,  0.58786465],
       [-1.84549744, -0.39222806, -0.27263346,  1.352671  ]])

In [69]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [70]:
data[mask]

array([[-0.13815771, -0.80074453, -0.94475482,  0.42506247],
       [-0.72402537, -1.05071225,  1.11418813, -0.91003131],
       [ 0.42499197, -0.79248955, -0.20310352, -0.80882149],
       [-0.48836748,  0.13455937, -0.22686739,  2.33568588]])

In [71]:
data[data < 0] = 0
data

array([[0.        , 0.        , 0.        , 0.42506247],
       [0.        , 0.29075391, 0.        , 0.        ],
       [0.        , 0.        , 1.11418813, 0.        ],
       [0.42499197, 0.        , 0.        , 0.        ],
       [0.        , 0.13455937, 0.        , 2.33568588],
       [0.        , 1.10141291, 0.26329184, 0.58786465],
       [0.        , 0.        , 0.        , 1.352671  ]])

In [72]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.29075391, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.10141291, 0.26329184, 0.58786465],
       [0.        , 0.        , 0.        , 1.352671  ]])

## Fancy indexing

In [73]:
import numpy as np
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [74]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [75]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [76]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [77]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

## Транспонирование и перстановка осей

In [78]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [80]:
import numpy as np
arr = np.random.rand(6, 3)
arr

array([[0.32425964, 0.7025034 , 0.88291276],
       [0.59174644, 0.75889039, 0.37846046],
       [0.69755114, 0.67656968, 0.74162087],
       [0.2763064 , 0.78497532, 0.60230492],
       [0.8317905 , 0.44410057, 0.10302997],
       [0.42508791, 0.19203801, 0.58046277]])

In [81]:
np.dot(arr.T, arr)

array([[1.89080614, 1.81673152, 1.52643184],
       [1.81673152, 2.37746237, 2.0392385 ],
       [1.52643184, 2.0392385 , 2.18309219]])

In [82]:
import numpy as np
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [83]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [84]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [85]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])