In [3]:
!pip install numpy

In [4]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 33.4 ms, sys: 14.8 ms, total: 48.2 ms
Wall time: 47.3 ms


In [7]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 528 ms, sys: 113 ms, total: 640 ms
Wall time: 645 ms


In [10]:
import numpy as np
# Генерация случайных данных
data = np.random.rand(2,3)
data

array([[0.11092979, 0.54631108, 0.94612703],
       [0.54536134, 0.8669498 , 0.68236164]])

In [11]:
data * 10

array([[1.10929791, 5.46311077, 9.4612703 ],
       [5.45361337, 8.66949799, 6.82361641]])

In [12]:
data + data

array([[0.22185958, 1.09262215, 1.89225406],
       [1.09072267, 1.7338996 , 1.36472328]])

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

In [15]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
import numpy as np
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int64')

In [21]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
import numpy as np
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
import numpy as np
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [30]:
arr1.dtype

dtype('float64')

In [31]:
arr2.dtype

dtype('int32')

In [32]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [34]:
import numpy as np
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [35]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [39]:
import numpy as np
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [40]:
import numpy as np
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [43]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [45]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [46]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [47]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [48]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr[5]

np.int64(5)

In [50]:
arr[5:8]

array([5, 6, 7])

In [51]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [52]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [53]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [54]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [55]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [56]:
arr2d[0][2]

np.int64(3)

In [57]:
arr2d[0, 2]

np.int64(3)

In [58]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
arr3d[1, 0]

array([7, 8, 9])

In [63]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [64]:
x[0]

array([7, 8, 9])

In [65]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])