In [1]:
import numpy as np
my_arr = np.arange(10000000)
my_list = list(range(10000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 3

CPU times: user 75.1 ms, sys: 53.3 ms, total: 128 ms
Wall time: 130 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 3 for x in my_list]

CPU times: user 3.76 s, sys: 1.34 s, total: 5.11 s
Wall time: 5.13 s


In [4]:
import numpy as np
data = np.random.rand(2, 3, 5)
data

array([[[0.50418327, 0.30998502, 0.20576094, 0.43261114, 0.47296478],
        [0.55969491, 0.62656971, 0.83365649, 0.21044215, 0.30475434],
        [0.04841615, 0.10486581, 0.47881817, 0.45049512, 0.17214947]],

       [[0.14836293, 0.39942899, 0.81508573, 0.28411221, 0.01803087],
        [0.14241712, 0.54588975, 0.92648602, 0.70696193, 0.82221933],
        [0.43722935, 0.58197608, 0.71475114, 0.9116281 , 0.06366709]]])

In [5]:
data * 10

array([[[5.04183272, 3.09985021, 2.05760937, 4.32611136, 4.72964782],
        [5.59694907, 6.26569707, 8.3365649 , 2.10442146, 3.04754344],
        [0.48416149, 1.0486581 , 4.78818174, 4.50495123, 1.72149466]],

       [[1.48362927, 3.99428985, 8.15085732, 2.84112206, 0.18030869],
        [1.42417119, 5.45889746, 9.26486021, 7.06961925, 8.22219326],
        [4.37229346, 5.81976084, 7.14751136, 9.11628098, 0.63667088]]])

In [6]:
data + data

array([[[1.00836654, 0.61997004, 0.41152187, 0.86522227, 0.94592956],
        [1.11938981, 1.25313941, 1.66731298, 0.42088429, 0.60950869],
        [0.0968323 , 0.20973162, 0.95763635, 0.90099025, 0.34429893]],

       [[0.29672585, 0.79885797, 1.63017146, 0.56822441, 0.03606174],
        [0.28483424, 1.09177949, 1.85297204, 1.41392385, 1.64443865],
        [0.87445869, 1.16395217, 1.42950227, 1.8232562 , 0.12733418]]])

In [7]:
data.shape

(2, 3, 5)

In [8]:
data.dtype

dtype('float64')

In [9]:
import numpy as np
data1 = [1, 2.3, 4, 5, 6]
arr1 = np.array(data1)
arr1

array([1. , 2.3, 4. , 5. , 6. ])

In [10]:
import numpy as np
data2 = [[[1, 2, 3, 4], [5, 6, 7, 8]], [[1, 2, 3, 4], [5, 6, 7, 8]]]
arr2 = np.array(data2)
arr2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [11]:
arr2.ndim

3

In [12]:
arr2.shape

(2, 2, 4)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int64')

In [15]:
import numpy as np
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
import numpy as np
np.zeros((3, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [17]:
import numpy as np
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float128)
arr2 = np.array([1, 2, 3], dtype=np.int16)

In [19]:
arr1.dtype

dtype('float128')

In [20]:
arr2.dtype

dtype('int16')

In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [22]:
float_arr = arr.astype(np.float128)
float_arr.dtype

dtype('float128')

In [23]:
import numpy as np
arr = np.array([3.7, -1.2, -21234.6, 0.5, 12.9, 10.1])
arr

array([ 3.70000e+00, -1.20000e+00, -2.12346e+04,  5.00000e-01,
        1.29000e+01,  1.01000e+01])

In [24]:
arr.astype(np.int8)

array([ 3, -1, 14,  0, 12, 10], dtype=int8)

In [25]:
import numpy as np
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [26]:
import numpy as np
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
import numpy as np
arr = np.array([[1., 3., 2.], [4., 6., 5.]])
arr

array([[1., 3., 2.],
       [4., 6., 5.]])

In [28]:
arr * arr

array([[ 1.,  9.,  4.],
       [16., 36., 25.]])

In [29]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Арифметические операции, в которых участвует скаляр, применяются к каждому элементу массива:

In [30]:
1 / arr

array([[1.        , 0.33333333, 0.5       ],
       [0.25      , 0.16666667, 0.2       ]])

In [31]:
arr ** 0.5

array([[1.        , 1.73205081, 1.41421356],
       [2.        , 2.44948974, 2.23606798]])

In [32]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [33]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Индексирование и вырезание

In [34]:
import numpy as np
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[5]

np.int64(5)

In [36]:
arr[5:8]

array([5, 6, 7])

In [37]:
arr[3:8] = 15
arr

array([ 0,  1,  2, 15, 15, 15, 15, 15,  8,  9, 10])

In [38]:
arr_slice = arr[5:8]
arr_slice

array([15, 15, 15])

In [39]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,    15,    15,    15, 12345,    15,     8,
           9,    10])

In [40]:
arr_slice[:] = 64
arr

array([ 0,  1,  2, 15, 15, 64, 64, 64,  8,  9, 10])

In [41]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [42]:
arr2d[0][2]

np.int64(3)

In [43]:
arr2d[0, 2]

np.int64(3)

In [44]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [46]:
old_values = arr3d[0].copy()
arr3d[0] = 12
arr3d

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[1, 1]

array([10, 11, 12])

In [49]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [50]:
x[0]

array([7, 8, 9])

Идексирование срезами

In [51]:
arr = np.array([ 0, 1, 2, 3, 4, 66, 64, 64, 8, 9])
arr

array([ 0,  1,  2,  3,  4, 66, 64, 64,  8,  9])

In [52]:
arr[1:7]

array([ 1,  2,  3,  4, 66, 64])

In [53]:
arr2d = np.array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [54]:
arr2d[:2]

array([[1, 0, 0],
       [4, 0, 0]])

In [55]:
arr2d[:2, 1:]

array([[0, 0],
       [0, 0]])

In [56]:
arr2d[:2, 2]

array([0, 0])

In [57]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [58]:
arr2d[:2, 1:] = -1
arr2d

array([[ 1, -1, -1],
       [ 4, -1, -1],
       [ 7,  8,  9]])

## Булево индексирование

In [59]:
import numpy as np
names = np.array(['Oliver', 'George', 'Oliver', 'Jack', 'George', 'George', 'Thomas'])
data = np.random.randn(7, 4)
names

array(['Oliver', 'George', 'Oliver', 'Jack', 'George', 'George', 'Thomas'],
      dtype='<U6')

In [60]:
data

array([[ 0.72888088,  0.21309188, -1.15368298,  0.22800662],
       [ 1.13415112, -0.79990553,  0.86377605, -1.05883103],
       [ 0.71458948,  0.58036206, -1.64210145, -0.98561379],
       [-2.27275354, -0.89368146, -0.04135452, -1.11700553],
       [ 0.24846516, -1.51622147,  0.76663844,  0.41401587],
       [ 0.98848352,  0.85915272, -0.36770642,  0.45117851],
       [ 2.18048028,  0.36502684, -0.35068735, -0.43151387]])

In [61]:
names == 'George'

array([False,  True, False, False,  True,  True, False])

In [62]:
data[names == 'George']

array([[ 1.13415112, -0.79990553,  0.86377605, -1.05883103],
       [ 0.24846516, -1.51622147,  0.76663844,  0.41401587],
       [ 0.98848352,  0.85915272, -0.36770642,  0.45117851]])

In [63]:
data[names == 'George', 2:]

array([[ 0.86377605, -1.05883103],
       [ 0.76663844,  0.41401587],
       [-0.36770642,  0.45117851]])

In [64]:
data[names == 'George', 2]

array([ 0.86377605,  0.76663844, -0.36770642])

In [65]:
names != 'George'

array([ True, False,  True,  True, False, False,  True])

In [66]:
data[~(names == 'George')]

array([[ 0.72888088,  0.21309188, -1.15368298,  0.22800662],
       [ 0.71458948,  0.58036206, -1.64210145, -0.98561379],
       [-2.27275354, -0.89368146, -0.04135452, -1.11700553],
       [ 2.18048028,  0.36502684, -0.35068735, -0.43151387]])

In [67]:
cond = names == 'George'
data[~cond]

array([[ 0.72888088,  0.21309188, -1.15368298,  0.22800662],
       [ 0.71458948,  0.58036206, -1.64210145, -0.98561379],
       [-2.27275354, -0.89368146, -0.04135452, -1.11700553],
       [ 2.18048028,  0.36502684, -0.35068735, -0.43151387]])

In [68]:
mask = (names == 'George') | (names == 'Oliver')
mask

array([ True,  True,  True, False,  True,  True, False])

In [69]:
data[mask]

array([[ 0.72888088,  0.21309188, -1.15368298,  0.22800662],
       [ 1.13415112, -0.79990553,  0.86377605, -1.05883103],
       [ 0.71458948,  0.58036206, -1.64210145, -0.98561379],
       [ 0.24846516, -1.51622147,  0.76663844,  0.41401587],
       [ 0.98848352,  0.85915272, -0.36770642,  0.45117851]])

In [70]:
data[data < 0] = 0
data

array([[0.72888088, 0.21309188, 0.        , 0.22800662],
       [1.13415112, 0.        , 0.86377605, 0.        ],
       [0.71458948, 0.58036206, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.24846516, 0.        , 0.76663844, 0.41401587],
       [0.98848352, 0.85915272, 0.        , 0.45117851],
       [2.18048028, 0.36502684, 0.        , 0.        ]])

In [71]:
data[names != 'Joe'] = 7
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

## Fancy indexing

In [72]:
import numpy as np
arr = np.empty((8, 5))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.]])

In [73]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [6., 6., 6., 6., 6.]])

In [74]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5., 5.],
       [3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.]])

In [75]:
arr = np.arange(40).reshape((8, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [76]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 5, 28, 36, 12])

## Транспонирование и перстановка осей

In [77]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [79]:
import numpy as np
arr = np.random.rand(6, 3)
arr

array([[0.36748158, 0.55881573, 0.41819128],
       [0.27385982, 0.25032159, 0.47438884],
       [0.85782058, 0.83541837, 0.94543771],
       [0.93849237, 0.33602223, 0.96003611],
       [0.72895391, 0.00636686, 0.34410958],
       [0.29388082, 0.67043334, 0.61628978]])

In [80]:
np.dot(arr.T, arr)

array([[2.44440572, 1.50756953, 2.42755189],
       [1.50756953, 1.63529211, 1.88024325],
       [2.42755189, 1.88024325, 2.71367502]])

In [81]:
import numpy as np
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [82]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [83]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [84]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])