In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 10.5 ms, sys: 7.05 ms, total: 17.5 ms
Wall time: 16.3 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 433 ms, sys: 99.5 ms, total: 533 ms
Wall time: 536 ms


In [4]:
import numpy as np
data = np.random.rand(2,3)
data

array([[0.5083743 , 0.88876932, 0.61719491],
       [0.2346658 , 0.672352  , 0.18158816]])

In [5]:
data * 10

array([[5.08374305, 8.88769316, 6.17194907],
       [2.34665798, 6.72351998, 1.81588158]])

In [6]:
data + data

array([[1.01674861, 1.77753863, 1.23438981],
       [0.4693316 , 1.344704  , 0.36317632]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [10]:
import numpy as np
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(2, 4)

In [13]:
arr1.dtype

dtype('float64')

In [14]:
arr2.dtype

dtype('int64')

In [15]:
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
import numpy as np
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
import numpy as np
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [19]:
arr1.dtype

dtype('float64')

In [20]:
arr2.dtype

dtype('int32')

In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [22]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [23]:
import numpy as np
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [24]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [25]:
import numpy as np
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [26]:
import numpy as np
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [29]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [32]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [33]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [34]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5]

np.int64(5)

In [36]:
arr[5:8]

array([5, 6, 7])

In [37]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [38]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [39]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [40]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [41]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [42]:
arr2d[0][2]

np.int64(3)

In [43]:
arr2d[0, 2]

np.int64(3)

In [44]:
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[1, 0]

array([7, 8, 9])

In [49]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [50]:
x[0]

array([7, 8, 9])

In [51]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [52]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [53]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [56]:
arr2d[:2, 2]

array([3, 6])

In [57]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [58]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Булево индексирование

In [59]:
import numpy as np
names = np.array(['Oliver', 'George', 'Oliver', 'Jack', 'George', 'George', 'Thomas'])
data = np.random.randn(7, 4)
names

array(['Oliver', 'George', 'Oliver', 'Jack', 'George', 'George', 'Thomas'],
      dtype='<U6')

In [60]:
data

array([[ 1.26518671,  0.22398921, -0.26070241, -0.62402065],
       [-2.32548466,  0.49396537, -0.02330027, -0.64448037],
       [ 0.81150553,  0.24721123, -0.29806288, -0.7660427 ],
       [-0.19344856,  0.93766773,  1.43219351, -0.08975996],
       [ 0.42074613,  0.3718779 , -0.9817327 ,  0.38682203],
       [-1.36006298, -1.0320878 , -1.6926369 , -0.11150818],
       [-1.1439729 ,  0.48901475, -0.65577158,  0.16437748]])

In [61]:
names == 'George'

array([False,  True, False, False,  True,  True, False])

In [62]:
data[names == 'George']

array([[-2.32548466,  0.49396537, -0.02330027, -0.64448037],
       [ 0.42074613,  0.3718779 , -0.9817327 ,  0.38682203],
       [-1.36006298, -1.0320878 , -1.6926369 , -0.11150818]])

In [63]:
data[names == 'George', 2:]

array([[-0.02330027, -0.64448037],
       [-0.9817327 ,  0.38682203],
       [-1.6926369 , -0.11150818]])

In [64]:
data[names == 'George', 2]

array([-0.02330027, -0.9817327 , -1.6926369 ])

In [65]:
names != 'George'

array([ True, False,  True,  True, False, False,  True])

In [66]:
data[~(names == 'George')]

array([[ 1.26518671,  0.22398921, -0.26070241, -0.62402065],
       [ 0.81150553,  0.24721123, -0.29806288, -0.7660427 ],
       [-0.19344856,  0.93766773,  1.43219351, -0.08975996],
       [-1.1439729 ,  0.48901475, -0.65577158,  0.16437748]])

In [67]:
cond = names == 'George'
data[~cond]

array([[ 1.26518671,  0.22398921, -0.26070241, -0.62402065],
       [ 0.81150553,  0.24721123, -0.29806288, -0.7660427 ],
       [-0.19344856,  0.93766773,  1.43219351, -0.08975996],
       [-1.1439729 ,  0.48901475, -0.65577158,  0.16437748]])

In [68]:
mask = (names == 'George') | (names == 'Oliver')
mask

array([ True,  True,  True, False,  True,  True, False])

In [69]:
data[mask]

array([[ 1.26518671,  0.22398921, -0.26070241, -0.62402065],
       [-2.32548466,  0.49396537, -0.02330027, -0.64448037],
       [ 0.81150553,  0.24721123, -0.29806288, -0.7660427 ],
       [ 0.42074613,  0.3718779 , -0.9817327 ,  0.38682203],
       [-1.36006298, -1.0320878 , -1.6926369 , -0.11150818]])

In [70]:
data[data < 0] = 0
data

array([[1.26518671, 0.22398921, 0.        , 0.        ],
       [0.        , 0.49396537, 0.        , 0.        ],
       [0.81150553, 0.24721123, 0.        , 0.        ],
       [0.        , 0.93766773, 1.43219351, 0.        ],
       [0.42074613, 0.3718779 , 0.        , 0.38682203],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.48901475, 0.        , 0.16437748]])

In [71]:
data[names != 'Joe'] = 7
data

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

## Fancy indexing

In [72]:
import numpy as np
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [73]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [74]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [75]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [76]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

## Транспонирование и перстановка осей

In [77]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [78]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [79]:
import numpy as np
arr = np.random.rand(6, 3)
arr

array([[0.59728694, 0.39448436, 0.23751296],
       [0.06166002, 0.91992749, 0.0470787 ],
       [0.70713822, 0.96349564, 0.41159157],
       [0.45117549, 0.79458754, 0.43848729],
       [0.48962064, 0.31441464, 0.03437323],
       [0.02315594, 0.69589333, 0.7828627 ]])

In [80]:
np.dot(arr.T, arr)

array([[1.30442202, 1.5022241 , 0.66861089],
       [1.5022241 , 3.1447018 , 1.43758374],
       [0.66861089, 1.43758374, 1.03436306]])

In [81]:
import numpy as np
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [82]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [83]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [84]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])