In [2]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
import numpy as np
x = np.random.randn(8)
y = np.random.randn(8)

In [6]:
x

array([-0.60112764, -1.70547849, -0.02393268, -0.05974746, -1.1242614 ,
       -0.24741569, -0.81913852, -0.56123083])

In [7]:
y

array([-1.08243078,  0.84458593,  0.90017596, -1.10114928,  2.18384197,
       -0.32916965,  0.55863982,  0.17292142])

In [8]:
np.maximum(x, y)

array([-0.60112764,  0.84458593,  0.90017596, -0.05974746,  2.18384197,
       -0.24741569,  0.55863982,  0.17292142])

In [9]:
import numpy as np
arr = np.random.randn(7) * 5
arr

array([-0.29530112, -1.51862366,  2.67035989,  7.218747  ,  7.52919048,
       -0.28806076, -4.65817186])

In [10]:
remaider, whole_part = np.modf(arr)
remaider

array([-0.29530112, -0.51862366,  0.67035989,  0.218747  ,  0.52919048,
       -0.28806076, -0.65817186])

In [11]:
whole_part

array([-0., -1.,  2.,  7.,  7., -0., -4.])

In [12]:
arr

array([-0.29530112, -1.51862366,  2.67035989,  7.218747  ,  7.52919048,
       -0.28806076, -4.65817186])