## Задание 1:
Привидите практические примеры всех унарных функций, перечисленных выше. В отдельной строке перед примером необходимо дать описание каждой функции.
Унарные u-функции: abs, fabs; sqrt; square; exp; log, log10, log2, log1p; sign; ceil; floor; rint; modf; isnan; isfinite, isinf; cos, cosh, sin, sinh, tan, tanh; arccos, arccosh, arcsin, arcsinh, arctan, arctanh; logical_not

In [1]:
import numpy as np

# 1. abs: Возвращает абсолютное значение каждого элемента массива, для целых чисел не меняет тип.
arr = np.array([-1, -2, 3, -4])
print("abs:", np.abs(arr), np.abs(arr).dtype)
print("fabs:", np.fabs(arr), np.fabs(arr).dtype)

# 2. fabs: Аналогично abs, но возвращает вещественные числа.
arr_float = np.array([-1.5, -2.5, 3.5, -4.5])
print("fabs:", np.fabs(arr_float))

# 3. sqrt: Возвращает квадратный корень каждого элемента массива.
arr_sqrt = np.array([1, 4, 9, 16])
print("sqrt:", np.sqrt(arr_sqrt))

# 4. square: Возвращает квадрат каждого элемента массива.
arr_square = np.array([1, 2, 3, 4])
print("square:", np.square(arr_square))

# 5. exp: Возвращает значение e, возведённое в степень каждого элемента массива.
arr_exp = np.array([0, 1, 2])
print("exp:", np.exp(arr_exp))

# 6. log: Возвращает логарифм по основанию e каждого элемента массива.
arr_log = np.array([1, np.e, np.e**2])
print("log:", np.log(arr_log))

# 7. log10: Возвращает логарифм по основанию 10 каждого элемента массива.
arr_log10 = np.array([10, 100, 1000])
print("log10:", np.log10(arr_log10))

# 8. log2: Возвращает логарифм по основанию 2 каждого элемента массива.
arr_log2 = np.array([2, 4, 8])
print("log2:", np.log2(arr_log2))

# 9. log1p: Возвращает логарифм (1 + x) для каждого элемента массива.
arr_log1p = np.array([0, 1, 2])
print("log1p:", np.log1p(arr_log1p))

# 10. sign: Возвращает знак каждого элемента массива (-1, 0 или 1).
arr_sign = np.array([-5, 0, 5])
print("sign:", np.sign(arr_sign))

# 11. ceil: Округляет каждый элемент массива вверх до ближайшего целого.
arr_ceil = np.array([1.1, 2.5, 3.9])
print("ceil:", np.ceil(arr_ceil))

# 12. floor: Округляет каждый элемент массива вниз до ближайшего целого.
arr_floor = np.array([1.1, 2.5, 3.9])
print("floor:", np.floor(arr_floor))

# 13. rint: Округляет каждый элемент массива до ближайшего целого.
arr_rint = np.array([1.1, 2.5, 3.9])
print("rint:", np.rint(arr_rint))

# 14. modf: Разделяет дробную и целую части каждого элемента массива.
arr_modf = np.array([1.5, 2.3, 3.7])
print("modf:", np.modf(arr_modf))

# 15. isnan: Возвращает булев массив, указывающий, является ли каждый элемент NaN (Not a Number).
arr_nan = np.array([1, 2, np.nan, 4])
print("isnan:", np.isnan(arr_nan))

# 16. isfinite: Возвращает булев массив, указывающий, является ли каждый элемент конечным.
arr_finite = np.array([1, 2, np.inf, -np.inf, np.nan])
print("isfinite:", np.isfinite(arr_finite))

# 17. isinf: Возвращает булев массив, указывающий, является ли каждый элемент бесконечным.
arr_inf = np.array([1, 2, np.inf, -np.inf])
print("isinf:", np.isinf(arr_inf))

# 18. cos: Косинус каждого элемента массива.
arr_cos = np.array([0, np.pi/2, np.pi])
print("cos:", np.cos(arr_cos))

# 19. cosh: Гиперболический косинус каждого элемента массива.
arr_cosh = np.array([0, 1, 2])
print("cosh:", np.cosh(arr_cosh))

# 20. sin: Синус каждого элемента массива.
arr_sin = np.array([0, np.pi/2, np.pi])
print("sin:", np.sin(arr_sin))

# 21. sinh: Гиперболический синус каждого элемента массива.
arr_sinh = np.array([0, 1, 2])
print("sinh:", np.sinh(arr_sinh))

# 22. tan: Тангенс каждого элемента массива.
arr_tan = np.array([0, np.pi/4, np.pi/2])
print("tan:", np.tan(arr_tan))

# 23. tanh: Гиперболический тангенс каждого элемента массива.
arr_tanh = np.array([0, 1, 2])
print("tanh:", np.tanh(arr_tanh))

# 24. arccos: Арккосинус каждого элемента массива.
arr_arccos = np.array([1, 0, -1])
print("arccos:", np.arccos(arr_arccos))

# 25. arccosh: Арккосинус гиперболический каждого элемента массива.
arr_arccosh = np.array([1, 2])
print("arccosh:", np.arccosh(arr_arccosh))

# 26. arcsin: Арксинус каждого элемента массива.
arr_arcsin = np.array([0, 0.5, 1])
print("arcsin:", np.arcsin(arr_arcsin))

# 27. arcsinh: Арксинус гиперболический каждого элемента массива.
arr_arcsinh = np.array([0, 1, 2])
print("arcsinh:", np.arcsinh(arr_arcsinh))

# 28. arctan: Арктангенс каждого элемента массива.
arr_arctan = np.array([0, 1, -1])
print("arctan:", np.arctan(arr_arctan))

# 29. arctanh: Арктангенс гиперболический каждого элемента массива.
arr_arctanh = np.array([0, 0.5])
print("arctanh:", np.arctanh(arr_arctanh))

# 30. logical_not: Возвращает логическое отрицание каждого элемента массива.
arr_logical = np.array([True, False, True])
print("logical_not:", np.logical_not(arr_logical))


abs: [1 2 3 4] int64
fabs: [1. 2. 3. 4.] float64
fabs: [1.5 2.5 3.5 4.5]
sqrt: [1. 2. 3. 4.]
square: [ 1  4  9 16]
exp: [1.         2.71828183 7.3890561 ]
log: [0. 1. 2.]
log10: [1. 2. 3.]
log2: [1. 2. 3.]
log1p: [0.         0.69314718 1.09861229]
sign: [-1  0  1]
ceil: [2. 3. 4.]
floor: [1. 2. 3.]
rint: [1. 2. 4.]
modf: (array([0.5, 0.3, 0.7]), array([1., 2., 3.]))
isnan: [False False  True False]
isfinite: [ True  True False False False]
isinf: [False False  True  True]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
cosh: [1.         1.54308063 3.76219569]
sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
sinh: [0.         1.17520119 3.62686041]
tan: [0.00000000e+00 1.00000000e+00 1.63312394e+16]
tanh: [0.         0.76159416 0.96402758]
arccos: [0.         1.57079633 3.14159265]
arccosh: [0.        1.3169579]
arcsin: [0.         0.52359878 1.57079633]
arcsinh: [0.         0.88137359 1.44363548]
arctan: [ 0.          0.78539816 -0.78539816]
arctanh: [0.         0.54930614]
logical_no

Привидите практические примеры всех бинарных функций, перечисленных выше. В отдельной строке перед примером необходимо дать описание каждой функции.
Бинарные u-функции: add; subtract; multiply; divide, floor_divide; power; maximum, fmax; minimum, fmin; mod; copysing; greater, greater_equal, less, less_equal, equal, not_equal; logical_and; logical_or; logical_xor.

In [2]:
import numpy as np

# 1. add: Возвращает сумму двух массивов.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("add:", np.add(arr1, arr2))

# 2. subtract: Возвращает разность двух массивов.
print("subtract:", np.subtract(arr1, arr2))

# 3. multiply: Возвращает произведение двух массивов.
print("multiply:", np.multiply(arr1, arr2))

# 4. divide: Возвращает частное двух массивов.
print("divide:", np.divide(arr1, arr2))

# 5. floor_divide: Возвращает целочисленное частное двух массивов.
print("floor_divide:", np.floor_divide(arr1, arr2))

# 6. power: Возвращает результат возведения элементов первого массива в степень элементов второго массива.
print("power:", np.power(arr1, arr2))

# 7. maximum: Возвращает массив, содержащий поэлементные максимумы двух массивов.
print("maximum:", np.maximum(arr1, arr2))

# 8. fmax: Возвращает массив, содержащий поэлементные максимумы двух массивов, игнорируя NaN.
arr3 = np.array([np.nan, 2, 3])
print("fmax:", np.fmax(arr3, arr2))

# 9. minimum: Возвращает массив, содержащий поэлементные минимумы двух массивов.
print("minimum:", np.minimum(arr1, arr2))

# 10. fmin: Возвращает массив, содержащий поэлементные минимумы двух массивов, игнорируя NaN.
print("fmin:", np.fmin(arr3, arr2))

# 11. mod: Возвращает остаток от деления элементов первого массива на элементы второго массива.
print("mod:", np.mod(arr1, arr2))

# 12. copysign: Возвращает массив, в котором элементы первого массива имеют знак элементов второго массива.
arr4 = np.array([-1, -2, -3])
print("copysign:", np.copysign(arr1, arr4))

# 13. greater: Возвращает булев массив, указывающий, являются ли элементы первого массива больше соответствующих элементов второго массива.
print("greater:", np.greater(arr1, arr2))

# 14. greater_equal: Возвращает булев массив, указывающий, являются ли элементы первого массива больше или равны соответствующим элементам второго массива.
print("greater_equal:", np.greater_equal(arr1, arr2))

# 15. less: Возвращает булев массив, указывающий, являются ли элементы первого массива меньше соответствующих элементов второго массива.
print("less:", np.less(arr1, arr2))

# 16. less_equal: Возвращает булев массив, указывающий, являются ли элементы первого массива меньше или равны соответствующим элементам второго массива.
print("less_equal:", np.less_equal(arr1, arr2))

# 17. equal: Возвращает булев массив, указывающий, равны ли элементы двух массивов.
print("equal:", np.equal(arr1, arr2))

# 18. not_equal: Возвращает булев массив, указывающий, не равны ли элементы двух массивов.
print("not_equal:", np.not_equal(arr1, arr2))

# 19. logical_and: Возвращает булев массив, указывающий, являются ли элементы двух массивов истинными одновременно.
arr5 = np.array([True, False, True])
arr6 = np.array([True, True, False])
print("logical_and:", np.logical_and(arr5, arr6))

# 20. logical_or: Возвращает булев массив, указывающий, являются ли элементы двух массивов истинными хотя бы один раз.
print("logical_or:", np.logical_or(arr5, arr6))

# 21. logical_xor: Возвращает булев массив, указывающий, являются ли элементы двух массивов истинными только в одном из них.
print("logical_xor:", np.logical_xor(arr5, arr6))


add: [5 7 9]
subtract: [-3 -3 -3]
multiply: [ 4 10 18]
divide: [0.25 0.4  0.5 ]
floor_divide: [0 0 0]
power: [  1  32 729]
maximum: [4 5 6]
fmax: [4. 5. 6.]
minimum: [1 2 3]
fmin: [4. 2. 3.]
mod: [1 2 3]
copysign: [-1. -2. -3.]
greater: [False False False]
greater_equal: [False False False]
less: [ True  True  True]
less_equal: [ True  True  True]
equal: [False False False]
not_equal: [ True  True  True]
logical_and: [ True False False]
logical_or: [ True  True  True]
logical_xor: [False  True  True]


## Задание 2:
Привидите практические примеры всех статических методов массива, перечисленных выше. В отдельной строке перед примером необходимо дать описание каждого метода.
Статические методы массива: sum; mean; std, var; min, max; argmin, argmax; cumsum; cumprod.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# 1. sum: Возвращает сумму всех элементов массива.
print("sum:", np.sum(arr))

# 2. mean: Возвращает среднее значение всех элементов массива.
print("mean:", np.mean(arr))

# 3. std: Возвращает стандартное отклонение элементов массива.
print("std:", np.std(arr))

# 4. var: Возвращает дисперсию элементов массива.
print("var:", np.var(arr))

# 5. min: Возвращает минимальное значение среди элементов массива.
print("min:", np.min(arr))

# 6. max: Возвращает максимальное значение среди элементов массива.
print("max:", np.max(arr))

# 7. argmin: Возвращает индекс минимального значения в массиве.
print("argmin:", np.argmin(arr))

# 8. argmax: Возвращает индекс максимального значения в массиве.
print("argmax:", np.argmax(arr))

# 9. cumsum: Возвращает массив, содержащий накопительную сумму элементов.
print("cumsum:", np.cumsum(arr))

# 10. cumprod: Возвращает массив, содержащий накопительное произведение элементов.
print("cumprod:", np.cumprod(arr))


sum: 15
mean: 3.0
std: 1.4142135623730951
var: 2.0
min: 1
max: 5
argmin: 0
argmax: 4
cumsum: [ 1  3  6 10 15]
cumprod: [  1   2   6  24 120]


# Задание 3:
Привидите практические примеры всех теоретико-множественных функций. В отдельной строке перед примером
необходимо дать описание каждой функции.
Теоретико-множественные функции, имеющиеся в NumPy: unique(x); intersect1d(x, y); union1d(x, y); in1d(x, y); setdiff1d(x, y);
setxor1d(x, y).

In [4]:
import numpy as np

# Создаем примеры массивов
x = np.array([1, 2, 3, 4, 5])
y = np.array([4, 5, 6, 7, 8])

# 1. unique: Возвращает уникальные элементы массива.
print("unique:", np.unique(x))

# 2. intersect1d: Возвращает пересечение двух массивов (общие элементы).
print("intersect1d:", np.intersect1d(x, y))

# 3. union1d: Возвращает объединение двух массивов (все уникальные элементы из обоих массивов).
print("union1d:", np.union1d(x, y))

# 4. in1d: Возвращает булев массив, указывающий, содержатся ли элементы первого массива во втором массиве.
print("in1d:", np.in1d(x, y))
print("isin:", np.isin(x, y))

# 5. setdiff1d: Возвращает элементы первого массива, которые не содержатся во втором массиве.
print("setdiff1d:", np.setdiff1d(x, y))

# 6. setxor1d: Возвращает элементы, которые находятся только в одном из массивов (симметрическая разность).
print("setxor1d:", np.setxor1d(x, y))

unique: [1 2 3 4 5]
intersect1d: [4 5]
union1d: [1 2 3 4 5 6 7 8]
in1d: [False False False  True  True]
isin: [False False False  True  True]
setdiff1d: [1 2 3]
setxor1d: [1 2 3 6 7 8]


/tmp/ipykernel_166025/3234036641.py:17: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print("in1d:", np.in1d(x, y))


In [5]:
import numpy as np
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [8]:
import numpy as np
x = np.random.randn(8)
y = np.random.randn(8)

In [9]:
x

array([-0.33378346, -0.74137205, -0.01682026, -0.38966262,  0.27006014,
        0.24760093, -0.98648396, -0.85801473])

In [10]:
y

array([-0.10429341,  0.25178481,  0.91575216, -0.21595735, -0.9414815 ,
       -0.35490174,  0.6331016 ,  1.31831559])

In [11]:
np.maximum(x, y)

array([-0.10429341,  0.25178481,  0.91575216, -0.21595735,  0.27006014,
        0.24760093,  0.6331016 ,  1.31831559])

In [12]:
import numpy as np
arr = np.random.randn(7) * 5
arr

array([-2.36165446, -1.47039664,  0.26867255,  2.25622905, -3.63966502,
        5.34656184, -7.64279523])

In [13]:
remaider, whole_part = np.modf(arr)
remaider

array([-0.36165446, -0.47039664,  0.26867255,  0.25622905, -0.63966502,
        0.34656184, -0.64279523])

In [14]:
whole_part

array([-2., -1.,  0.,  2., -3.,  5., -7.])

In [15]:
arr

array([-2.36165446, -1.47039664,  0.26867255,  2.25622905, -3.63966502,
        5.34656184, -7.64279523])

In [16]:
np.sqrt(arr)

/tmp/ipykernel_166025/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan, 0.51833633, 1.50207492,        nan,
       2.31226336,        nan])

In [17]:
np.sqrt(arr, arr)

/tmp/ipykernel_166025/269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan,        nan, 0.51833633, 1.50207492,        nan,
       2.31226336,        nan])

In [18]:
arr

array([       nan,        nan, 0.51833633, 1.50207492,        nan,
       2.31226336,        nan])

Программирование с применением массивов

In [19]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [20]:
result = [(x if c else y)
for x, y, c in zip(xarr, yarr, cond)]
result

[np.float64(1.1),
 np.float64(2.2),
 np.float64(1.3),
 np.float64(1.4),
 np.float64(2.5)]

In [21]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [22]:
import numpy as np
arr = np.random.randn(4, 4)
arr

array([[ 0.01710871,  0.25285783,  1.27207102,  1.2401418 ],
       [ 0.01596141,  0.9715564 , -0.73975863,  0.35706666],
       [-1.00802773,  2.85611489,  0.97576   ,  1.69697803],
       [ 0.44143211, -1.46323324, -1.41160319,  0.40173362]])

In [23]:
arr > 0

array([[ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False,  True,  True,  True],
       [ True, False, False,  True]])

In [24]:
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2,  2],
       [ 2,  2, -2,  2],
       [-2,  2,  2,  2],
       [ 2, -2, -2,  2]])

In [25]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        ,  2.        , -0.73975863,  2.        ],
       [-1.00802773,  2.        ,  2.        ,  2.        ],
       [ 2.        , -1.46323324, -1.41160319,  2.        ]])

Математические и статистические операции

In [26]:
import numpy as np
arr = np.random.randn(5, 4)
arr

array([[ 0.41127618, -0.63042735, -0.12855979,  0.19138835],
       [-1.37557362,  0.27606543, -0.62464975, -1.10094754],
       [-0.39738567, -0.62226964,  0.79419431,  0.12993419],
       [ 0.19688046,  2.23593499, -0.50938238, -1.55275448],
       [ 0.4011385 , -1.257572  ,  0.1730135 , -0.84672223]])

In [27]:
arr.mean()

np.float64(-0.21182092625119547)

In [28]:
np.mean(arr)

np.float64(-0.21182092625119547)

In [29]:
arr.sum()

np.float64(-4.236418525023909)

In [30]:
arr.mean(axis=1)

array([-0.03908065, -0.70627637, -0.0238817 ,  0.09266965, -0.38253556])

In [31]:
arr.sum(axis=0)

array([-7.63664150e-01,  1.73143347e-03, -2.95384112e-01, -3.17910170e+00])

In [32]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28])

In [33]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.cumsum(axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [35]:
arr.cumprod(axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]])

Методы булевых массивов

In [36]:
import numpy as np
arr = np.random.randn(100)
(arr > 0).sum() # количество положительных значений

np.int64(50)

In [37]:
import numpy as np
bools = np.array([False, False, True, False])
bools.any()

np.True_

In [38]:
bools.all()

np.False_

Сортировка

In [39]:
import numpy as np
arr = np.random.randn(6)
arr

array([-0.37790478, -1.02727861, -1.95583856,  2.07813476, -1.50939413,
        0.22459518])

In [40]:
arr.sort()
arr

array([-1.95583856, -1.50939413, -1.02727861, -0.37790478,  0.22459518,
        2.07813476])

In [41]:
import numpy as np
arr = np.random.randn(5, 3)
arr

array([[ 0.1081671 ,  0.12771816, -0.8507292 ],
       [-0.72220435,  1.56629079,  1.09161824],
       [ 1.07215575,  1.2070233 ,  0.39048487],
       [-1.26029926,  1.24645294, -2.85240949],
       [-0.88037734, -1.6546885 , -1.48284891]])

In [42]:
arr.sort(1)
arr

array([[-0.8507292 ,  0.1081671 ,  0.12771816],
       [-0.72220435,  1.09161824,  1.56629079],
       [ 0.39048487,  1.07215575,  1.2070233 ],
       [-2.85240949, -1.26029926,  1.24645294],
       [-1.6546885 , -1.48284891, -0.88037734]])

In [43]:
import numpy as np
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5%ый квантиль

np.float64(-1.7546329242346688)

Удаление дубликатов и другие теоретико-множественные операции

In [44]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [45]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4 ,4])
np.unique(ints)

array([1, 2, 3, 4])

In [46]:
sorted(set(names))

[np.str_('Bob'), np.str_('Joe'), np.str_('Will')]

In [47]:
import numpy as np
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

/tmp/ipykernel_166025/3962354450.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(values, [2, 3, 6])


array([ True, False, False,  True,  True, False,  True])

Файловый ввод-вывод массивов

In [48]:
import numpy as np
arr = np.arange(11)
np.save('some_array', arr)

In [49]:
np.load('some_array.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.savez('array_archive.npz', a=arr, b=arr)

In [51]:
arch = np.load('array_archive.npz')
arch['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

Линейная алгебра

In [53]:
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [54]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [55]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [56]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [57]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [58]:
x @ np.ones(3)

array([ 6., 15.])

In [59]:
from numpy.linalg import inv, qr
X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 1.91303297, -1.9620515 , -0.13563514, -2.67569641,  0.04902593],
       [-1.9620515 ,  3.4388133 , -1.50673499,  2.25643959, -0.13024496],
       [-0.13563514, -1.50673499,  3.38334682,  1.63804877,  0.18883042],
       [-2.67569641,  2.25643959,  1.63804877,  5.10225245,  0.04167317],
       [ 0.04902593, -0.13024496,  0.18883042,  0.04167317,  0.14364901]])

In [60]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  4.48778585e-16, -3.04911108e-16,
        -9.89958644e-16,  1.97788704e-17],
       [ 2.56817752e-16,  1.00000000e+00,  5.74695300e-17,
         4.95905893e-16, -2.19553593e-17],
       [ 2.17247599e-16, -8.26588144e-16,  1.00000000e+00,
        -2.62755221e-16,  6.78064696e-18],
       [ 2.85465114e-16,  4.15203919e-16, -4.90454245e-16,
         1.00000000e+00, -3.01536308e-17],
       [-1.89982769e-16,  1.33874902e-18, -2.00774772e-17,
        -1.22767579e-17,  1.00000000e+00]])

In [61]:
q, r = qr(mat)
r

array([[-4.39176129, -1.34588505, -0.01363004, -1.787145  ,  1.8804458 ],
       [ 0.        , -2.07070395, -1.83662819,  1.60265745, -0.3599998 ],
       [ 0.        ,  0.        , -0.56350129,  0.13307711,  6.54956072],
       [ 0.        ,  0.        ,  0.        , -0.15649453,  0.20797962],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  3.59452076]])

In [62]:
import numpy as np
samples = np.random.normal(size=(4, 4))
samples

array([[-0.12018228,  1.741369  , -1.32563361,  0.63094972],
       [-0.14474621,  1.83339959,  1.71948201,  0.82249638],
       [ 0.03135066,  2.3677898 ,  0.49067288,  1.03958683],
       [-0.68720791,  0.01860778,  1.57798924, -1.9083512 ]])

In [63]:
from random import normalvariate
N = 10000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

5.75 s ± 148 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [64]:
%timeit np.random.normal(size=N)

213 ms ± 4.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [65]:
np.random.seed(12345)

In [66]:
np.random.randn(10)

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474])

In [67]:
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])