In [1]:
import pandas as pd
from pandas import Series, DataFrame

In [2]:
import pandas as pd
from pandas import Series, DataFrame
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
import pandas as pd
from pandas import Series, DataFrame
obj2 = Series([4, 7, -5, 3, 3], index=['d', 'b', 'a', 'c', 'e'])
obj2

d    4
b    7
a   -5
c    3
e    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c', 'e'], dtype='object')

In [7]:
obj2['e']

np.int64(3)

In [8]:
obj2['d'] = 6

In [9]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [10]:
obj2[obj2 > 0]

d    6
b    7
c    3
e    3
dtype: int64

In [11]:
obj2 * 3

d    18
b    21
a   -15
c     9
e     9
dtype: int64

In [12]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
e      20.085537
dtype: float64

In [13]:
'b' in obj2

True

In [14]:
'e' in obj2

True

In [15]:
import pandas as pd
from pandas import Series, DataFrame
sdata = {'Ohio': 3333, 'Texas': 71200, 'Oregon': 10000, 'Utah': 115000}
obj3 = pd.Series(sdata)
obj3

Ohio        3333
Texas      71200
Oregon     10000
Utah      115000
dtype: int64

In [16]:
states = ['California', 'Ohio', 'Oregon', 'Texas', 'Chelyabinsk']
obj4 = pd.Series(sdata, index=states)
obj4

California         NaN
Ohio            3333.0
Oregon         10000.0
Texas          71200.0
Chelyabinsk        NaN
dtype: float64

In [17]:
pd.isnull(obj4)

California      True
Ohio           False
Oregon         False
Texas          False
Chelyabinsk     True
dtype: bool

In [18]:
pd.notnull(obj4)

California     False
Ohio            True
Oregon          True
Texas           True
Chelyabinsk    False
dtype: bool

In [19]:
obj4.isnull()

California      True
Ohio           False
Oregon         False
Texas          False
Chelyabinsk     True
dtype: bool

In [20]:
obj3

Ohio        3333
Texas      71200
Oregon     10000
Utah      115000
dtype: int64

In [21]:
obj4

California         NaN
Ohio            3333.0
Oregon         10000.0
Texas          71200.0
Chelyabinsk        NaN
dtype: float64

In [22]:
obj3 + obj4

California          NaN
Chelyabinsk         NaN
Ohio             6666.0
Oregon          20000.0
Texas          142400.0
Utah                NaN
dtype: float64

In [23]:
obj4.name = 'population'

In [24]:
obj4.index.name = 'state'

In [25]:
obj4

state
California         NaN
Ohio            3333.0
Oregon         10000.0
Texas          71200.0
Chelyabinsk        NaN
Name: population, dtype: float64

In [26]:
obj = Series([4, 7, -5, 3])

In [27]:
obj.index = ['One', 'Two', 'Three', 'Four']
obj

One      4
Two      7
Three   -5
Four     3
dtype: int64

## Объект DataFrame

In [28]:
import pandas as pd
from pandas import Series, DataFrame
data = {
    'city': ['Volgograd', 'Novosibirsk', 'Petropavlovsk-Kamchatsky', 'Zelenograd', 'Krasnoyarsk', 'Chelyabinsk'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.2, 1.5, 2.0, 1.8, 2.3, 2.7]
}
frame = pd.DataFrame(data)
frame


city  year  pop
0                 Volgograd  2000  1.2
1               Novosibirsk  2001  1.5
2  Petropavlovsk-Kamchatsky  2002  2.0
3                Zelenograd  2001  1.8
4               Krasnoyarsk  2002  2.3
5               Chelyabinsk  2003  2.7

In [29]:
frame.head()

city  year  pop
0                 Volgograd  2000  1.2
1               Novosibirsk  2001  1.5
2  Petropavlovsk-Kamchatsky  2002  2.0
3                Zelenograd  2001  1.8
4               Krasnoyarsk  2002  2.3

In [30]:
pd.DataFrame(data, columns=['year', 'city', 'pop'])

year                      city  pop
0  2000                 Volgograd  1.2
1  2001               Novosibirsk  1.5
2  2002  Petropavlovsk-Kamchatsky  2.0
3  2001                Zelenograd  1.8
4  2002               Krasnoyarsk  2.3
5  2003               Chelyabinsk  2.7

In [31]:
frame2 = pd.DataFrame(data, columns=['year', 'city', 'pop', 'debt'],
index=['one', 'two', 'three', 'four',
'five', 'six'])

frame2.columns

Index(['year', 'city', 'pop', 'debt'], dtype='object')

In [32]:
frame2['city']

one                     Volgograd
two                   Novosibirsk
three    Petropavlovsk-Kamchatsky
four                   Zelenograd
five                  Krasnoyarsk
six                   Chelyabinsk
Name: city, dtype: object

In [33]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [34]:
frame2.loc['three']

year                        2002
city    Petropavlovsk-Kamchatsky
pop                          2.0
debt                         NaN
Name: three, dtype: object

In [35]:
frame2['debt'] = 16.5
frame2

year                      city  pop  debt
one    2000                 Volgograd  1.2  16.5
two    2001               Novosibirsk  1.5  16.5
three  2002  Petropavlovsk-Kamchatsky  2.0  16.5
four   2001                Zelenograd  1.8  16.5
five   2002               Krasnoyarsk  2.3  16.5
six    2003               Chelyabinsk  2.7  16.5

In [36]:
frame2['debt'] = np.arange(6.)
frame2

year                      city  pop  debt
one    2000                 Volgograd  1.2   0.0
two    2001               Novosibirsk  1.5   1.0
three  2002  Petropavlovsk-Kamchatsky  2.0   2.0
four   2001                Zelenograd  1.8   3.0
five   2002               Krasnoyarsk  2.3   4.0
six    2003               Chelyabinsk  2.7   5.0

In [37]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year                      city  pop  debt
one    2000                 Volgograd  1.2   NaN
two    2001               Novosibirsk  1.5  -1.2
three  2002  Petropavlovsk-Kamchatsky  2.0   NaN
four   2001                Zelenograd  1.8  -1.5
five   2002               Krasnoyarsk  2.3  -1.7
six    2003               Chelyabinsk  2.7   NaN

In [38]:
frame2['eastern'] = frame2.city == 'Zelenograd'
frame2

year                      city  pop  debt  eastern
one    2000                 Volgograd  1.2   NaN    False
two    2001               Novosibirsk  1.5  -1.2    False
three  2002  Petropavlovsk-Kamchatsky  2.0   NaN    False
four   2001                Zelenograd  1.8  -1.5     True
five   2002               Krasnoyarsk  2.3  -1.7    False
six    2003               Chelyabinsk  2.7   NaN    False

In [39]:
del frame2['eastern']
frame2.columns

Index(['year', 'city', 'pop', 'debt'], dtype='object')

In [40]:
frame2.columns

Index(['year', 'city', 'pop', 'debt'], dtype='object')

In [41]:
pop = {'Volgograd': {2000: 1.2, 2001: 1.3},
'Novosibirsk': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [42]:
frame3 = DataFrame(pop)
frame3

Volgograd  Novosibirsk
2000        1.2          1.5
2001        1.3          1.7
2002        NaN          3.6

In [43]:
frame3.T

2000  2001  2002
Volgograd     1.2   1.3   NaN
Novosibirsk   1.5   1.7   3.6

In [44]:
DataFrame(pop, index=[2001, 2002, 2003])

Volgograd  Novosibirsk
2001        1.3          1.7
2002        NaN          3.6
2003        NaN          NaN

In [45]:
pdata = {'Volgograd': frame3['Volgograd'][:-1],
'Novosibirsk':frame3['Novosibirsk'][:2]}
DataFrame(pdata)

Volgograd  Novosibirsk
2000        1.2          1.5
2001        1.3          1.7

In [46]:
frame3.index.name = 'year'; frame3.columns.name = 'gorodok'
frame3

gorodok  Volgograd  Novosibirsk
year                           
2000           1.2          1.5
2001           1.3          1.7
2002           NaN          3.6

In [47]:
frame3.values

array([[1.2, 1.5],
       [1.3, 1.7],
       [nan, 3.6]])

In [48]:
frame2.values

array([[2000, 'Volgograd', 1.2, nan],
       [2001, 'Novosibirsk', 1.5, -1.2],
       [2002, 'Petropavlovsk-Kamchatsky', 2.0, nan],
       [2001, 'Zelenograd', 1.8, -1.5],
       [2002, 'Krasnoyarsk', 2.3, -1.7],
       [2003, 'Chelyabinsk', 2.7, nan]], dtype=object)

Индексные объекты

In [49]:
import pandas as pd
from pandas import Series, DataFrame
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [50]:
index[1:]

Index(['b', 'c'], dtype='object')

In [52]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [53]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [54]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [55]:
obj2.index is labels

True

In [56]:
frame3

gorodok  Volgograd  Novosibirsk
year                           
2000           1.2          1.5
2001           1.3          1.7
2002           NaN          3.6

In [57]:
frame3.columns

Index(['Volgograd', 'Novosibirsk'], dtype='object', name='gorodok')

In [58]:
'Novosibirsk' in frame3.columns

True

In [59]:
2003 in frame2.index

False

In [60]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Задание 1
Привидите практические примеры всех аргументов конструктора DataFrame со своими примерами, перечисленных выше.
В отдельной строке перед примером необходимо дать описание каждого аргумента.
Аргументы конструктора DataFrame: двумерный ndarray; словарь массивов, списков или кортежей; структурированный массив NumPy; словарь объектов Series; словарь словарей; список словарей или объектов Series; список списков или кортежей; другой объект DataFrame; объект Numpy MaskedArray.

In [61]:
import pandas as pd
import numpy as np

In [62]:
# 1. Двумерный ndarray
# Создание DataFrame из двумерного массива NumPy.
data_ndarray = np.array([[1, 2, 3], [4, 5, 6]])
df_ndarray = pd.DataFrame(data_ndarray, columns=['A', 'B', 'C'])
df_ndarray

A  B  C
0  1  2  3
1  4  5  6

In [63]:
# 2. Словарь массивов, списков или кортежей
# Создание DataFrame из словаря, где ключи - названия столбцов, а значения - списки.
data_dict = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}
df_dict = pd.DataFrame(data_dict)
df_dict

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [64]:
# 3. Структурированный массив NumPy
# Создание DataFrame из структурированного массива NumPy.
structured_array = np.array([(1, 'Alice', 25), (2, 'Bob', 30)],
                            dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'i4')])
df_structured = pd.DataFrame(structured_array)
df_structured

id   name  age
0   1  Alice   25
1   2    Bob   30

In [65]:
# 4. Словарь объектов Series
# Создание DataFrame из словаря, где ключи - названия столбцов, а значения - объекты Series.
series_dict = {
    'A': pd.Series([1, 2, 3]),
    'B': pd.Series([4, 5, 6]),
    'C': pd.Series([7, 8, 9])
}
df_series = pd.DataFrame(series_dict)
df_series

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [66]:
# 5. Словарь словарей
# Создание DataFrame из словаря словарей.
data_nested_dict = {
    'col1': {'A': 1, 'B': 2, 'C': 3},
    'col2': {'A': 4, 'B': 5, 'C': 6}
}
df_nested_dict = pd.DataFrame(data_nested_dict)
df_nested_dict

col1  col2
A     1     4
B     2     5
C     3     6

In [67]:
# 6. Список словарей или объектов Series
# Создание DataFrame из списка словарей.
data_list_of_dicts = [
    {'A': 1, 'B': 2, 'C': 3},
    {'A': 4, 'B': 5, 'C': 6}
]
df_list_of_dicts = pd.DataFrame(data_list_of_dicts)
df_list_of_dicts

A  B  C
0  1  2  3
1  4  5  6

In [68]:
# 7. Список списков или кортежей
# Создание DataFrame из списка списков.
data_list_of_lists = [
    [1, 2, 3],
    [4, 5, 6]
]
df_list_of_lists = pd.DataFrame(data_list_of_lists, columns=['A', 'B', 'C'])
df_list_of_lists

A  B  C
0  1  2  3
1  4  5  6

In [69]:
# 8. Другой объект DataFrame
# Создание DataFrame из другого DataFrame.
df_copy = pd.DataFrame(df_list_of_lists)
df_copy

A  B  C
0  1  2  3
1  4  5  6

In [70]:
# 9. Объект Numpy MaskedArray
# Создание DataFrame из объекта Numpy MaskedArray.
masked_array = np.ma.array([[1, 2, 3], [4, np.ma.masked, 6]], mask=[[0, 0, 0], [0, 1, 0]])
df_masked_array = pd.DataFrame(masked_array)
df_masked_array

/home/evgen/Documents/University/master-1/python-ai/.venv/lib64/python3.12/site-packages/numpy/ma/core.py:2881: UserWarning: Warning: converting a masked element to nan.
  _data = np.array(data, dtype=dtype, copy=copy,


0    1    2
0  1.0  2.0  3.0
1  4.0  NaN  6.0

## Задание 2
Привидите практические примеры всех методов и свойств объекта Index со своими примерами, перечисленных выше. В
отдельной строке перед примером необходимо дать описание каждого метода и свойства.

Методы и свойства объекта Index: append; diff; intersection; union; isin; delete; drop; insert; is_monotonic; is_unique; unique.

In [71]:
import pandas as pd

index1 = pd.Index([1, 2, 3, 4, 5])
index2 = pd.Index([4, 5, 6, 7, 8])

In [72]:

# 1. append
# Метод append добавляет элементы из другого объекта Index.
index_appended = index1.append(index2)
index_appended

Index([1, 2, 3, 4, 5, 4, 5, 6, 7, 8], dtype='int64')

In [73]:
# 2. diff
# Метод diff возвращает разности между элементами.
index_diff = index1.diff()
index_diff

Index([nan, 1.0, 1.0, 1.0, 1.0], dtype='float64')

In [74]:
# 3. intersection
# Метод intersection возвращает пересечение двух объектов Index.
index_intersection = index1.intersection(index2)
index_intersection

Index([4, 5], dtype='int64')

In [75]:
# 4. union
# Метод union возвращает объединение двух объектов Index.
index_union = index1.union(index2)
index_union

Index([1, 2, 3, 4, 5, 6, 7, 8], dtype='int64')

In [76]:
# 5. isin
# Метод isin проверяет, содержится ли каждый элемент в другом объекте.
isin_result = index1.isin([1, 2, 6])
isin_result

array([ True,  True, False, False, False])

In [77]:
# 6. delete
# Метод delete удаляет элемент по указанному индексу.
index_deleted = index1.delete(2)  # Удаляем элемент с индексом 2 (т.е. 3)
index_deleted

Index([1, 2, 4, 5], dtype='int64')

In [78]:
# 7. drop
# Метод drop удаляет указанные элементы.
index_dropped = index1.drop(3)
index_dropped

Index([1, 2, 4, 5], dtype='int64')

In [79]:
# 8. insert
# Метод insert вставляет элемент по указанному индексу.
index_inserted = index1.insert(2, 10)  # Вставляем 10 на позицию 2
index_inserted

Index([1, 2, 10, 3, 4, 5], dtype='int64')

In [80]:
# 9. is_monotonic
# Свойство is_monotonic проверяет, является ли индекс монотонным (возрастающим или убывающим).
print(index1.is_monotonic_increasing)
print(index1.is_monotonic_decreasing)

True
False


In [81]:
# 10. is_unique
# Свойство is_unique проверяет, уникальны ли все элементы в индексе.
is_unique_result = index1.is_unique
is_unique_result

True

In [82]:
# 11. unique
# Метод unique возвращает уникальные значения в индексе.
index_unique = index1.unique()
index_unique

Index([1, 2, 3, 4, 5], dtype='int64')